# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alarm(object):
    def setupUi(self, Alarm):
        Alarm.setObjectName("Alarm")
        Alarm.resize(400, 600)
        Alarm.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.centralwidget = QtWidgets.QWidget(Alarm)
        self.centralwidget.setObjectName("centralwidget")
        self.timeNow = QtWidgets.QLCDNumber(self.centralwidget)
        self.timeNow.setGeometry(QtCore.QRect(90, 150, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.timeNow.setFont(font)
        self.timeNow.setObjectName("timeNow")
        self.buttonAlarm = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAlarm.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.buttonAlarm.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 0);")
        self.buttonAlarm.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("alarm-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarm.setIcon(icon)
        self.buttonAlarm.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarm.setObjectName("buttonAlarm")
        self.dateNow = QtWidgets.QLabel(self.centralwidget)
        self.dateNow.setGeometry(QtCore.QRect(90, 110, 211, 31))
        self.dateNow.setObjectName("dateNow")
        self.buttonTimer = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTimer.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.buttonTimer.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonTimer.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimer.setIcon(icon1)
        self.buttonTimer.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimer.setObjectName("buttonTimer")
        self.buttonStopwatch = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStopwatch.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.buttonStopwatch.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonStopwatch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("stopwatch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStopwatch.setIcon(icon2)
        self.buttonStopwatch.setIconSize(QtCore.QSize(32, 32))
        self.buttonStopwatch.setObjectName("buttonStopwatch")
        self.buttonTimerPlus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTimerPlus.setGeometry(QtCore.QRect(10, 510, 381, 81))
        self.buttonTimerPlus.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 0);")
        self.buttonTimerPlus.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimerPlus.setIcon(icon3)
        self.buttonTimerPlus.setIconSize(QtCore.QSize(54, 54))
        self.buttonTimerPlus.setObjectName("buttonTimerPlus")
        Alarm.setCentralWidget(self.centralwidget)

        self.retranslateUi(Alarm)
        QtCore.QMetaObject.connectSlotsByName(Alarm)

    def retranslateUi(self, Alarm):
        _translate = QtCore.QCoreApplication.translate
        Alarm.setWindowTitle(_translate("Alarm", "Alarm"))
        self.buttonAlarm.setWhatsThis(_translate("Alarm", "<html><head/><body><p><br/></p></body></html>"))
        self.dateNow.setText(_translate("Alarm", "Дата:"))
        self.buttonTimer.setWhatsThis(_translate("Alarm", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonStopwatch.setWhatsThis(_translate("Alarm", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonTimerPlus.setWhatsThis(_translate("Alarm", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Alarm = QtWidgets.QMainWindow()
    ui = Ui_Alarm()
    ui.setupUi(Alarm)
    Alarm.show()
    sys.exit(app.exec_())
