# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlarmDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelTime = QtWidgets.QLabel(Dialog)
        self.labelTime.setGeometry(QtCore.QRect(40, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTime.setFont(font)
        self.labelTime.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.labelTime.setObjectName("labelTime")
        self.timeSet = QtWidgets.QLCDNumber(Dialog)
        self.timeSet.setGeometry(QtCore.QRect(200, 60, 151, 41))
        self.timeSet.setObjectName("timeSet")
        self.labelDay = QtWidgets.QLabel(Dialog)
        self.labelDay.setGeometry(QtCore.QRect(40, 110, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelDay.setFont(font)
        self.labelDay.setStyleSheet("background-color: rgb(175, 175, 175);")
        self.labelDay.setObjectName("labelDay")
        self.buttonAlarmMonday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmMonday.setGeometry(QtCore.QRect(200, 110, 25, 25))
        self.buttonAlarmMonday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmMonday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmMonday.setObjectName("buttonAlarmMonday")
        self.buttonAlarmTuesday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmTuesday.setGeometry(QtCore.QRect(230, 110, 25, 25))
        self.buttonAlarmTuesday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmTuesday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmTuesday.setObjectName("buttonAlarmTuesday")
        self.buttonAlarmWednesday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmWednesday.setGeometry(QtCore.QRect(260, 110, 25, 25))
        self.buttonAlarmWednesday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmWednesday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmWednesday.setObjectName("buttonAlarmWednesday")
        self.buttonAlarmThursday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmThursday.setGeometry(QtCore.QRect(290, 110, 25, 25))
        self.buttonAlarmThursday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmThursday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmThursday.setObjectName("buttonAlarmThursday")
        self.buttonAlarmFriday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmFriday.setGeometry(QtCore.QRect(320, 110, 25, 25))
        self.buttonAlarmFriday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmFriday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmFriday.setObjectName("buttonAlarmFriday")
        self.buttonAlarmSaturday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmSaturday.setGeometry(QtCore.QRect(200, 140, 25, 25))
        self.buttonAlarmSaturday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmSaturday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmSaturday.setObjectName("buttonAlarmSaturday")
        self.buttonAlarmSunday = QtWidgets.QPushButton(Dialog)
        self.buttonAlarmSunday.setGeometry(QtCore.QRect(230, 140, 25, 25))
        self.buttonAlarmSunday.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);")
        self.buttonAlarmSunday.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmSunday.setObjectName("buttonAlarmSunday")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTime.setText(_translate("Dialog", "Время"))
        self.labelDay.setText(_translate("Dialog", "День недели"))
        self.buttonAlarmMonday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmMonday.setText(_translate("Dialog", "ПН"))
        self.buttonAlarmTuesday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmTuesday.setText(_translate("Dialog", "ВТ"))
        self.buttonAlarmWednesday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmWednesday.setText(_translate("Dialog", "СР"))
        self.buttonAlarmThursday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmThursday.setText(_translate("Dialog", "ЧТ"))
        self.buttonAlarmFriday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmFriday.setText(_translate("Dialog", "ПТ"))
        self.buttonAlarmSaturday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmSaturday.setText(_translate("Dialog", "СБ"))
        self.buttonAlarmSunday.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmSunday.setText(_translate("Dialog", "ВС"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
