# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stopwatch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stopwatch(object):
    def setupUi(self, Stopwatch):
        Stopwatch.setObjectName("Stopwatch")
        Stopwatch.resize(400, 600)
        Stopwatch.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.buttonTimer = QtWidgets.QPushButton(Stopwatch)
        self.buttonTimer.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.buttonTimer.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonTimer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimer.setIcon(icon)
        self.buttonTimer.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimer.setObjectName("buttonTimer")
        self.buttonStopwatch = QtWidgets.QPushButton(Stopwatch)
        self.buttonStopwatch.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.buttonStopwatch.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 0);")
        self.buttonStopwatch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("stopwatch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStopwatch.setIcon(icon1)
        self.buttonStopwatch.setIconSize(QtCore.QSize(32, 32))
        self.buttonStopwatch.setObjectName("buttonStopwatch")
        self.buttonAlarm_2 = QtWidgets.QPushButton(Stopwatch)
        self.buttonAlarm_2.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.buttonAlarm_2.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonAlarm_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("alarm-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarm_2.setIcon(icon2)
        self.buttonAlarm_2.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarm_2.setObjectName("buttonAlarm_2")
        self.MainTimer = QtWidgets.QLCDNumber(Stopwatch)
        self.MainTimer.setGeometry(QtCore.QRect(90, 200, 211, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.MainTimer.setFont(font)
        self.MainTimer.setObjectName("MainTimer")
        self.buttonAlarmRefresh = QtWidgets.QPushButton(Stopwatch)
        self.buttonAlarmRefresh.setGeometry(QtCore.QRect(250, 350, 51, 51))
        self.buttonAlarmRefresh.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonAlarmRefresh.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarmRefresh.setIcon(icon3)
        self.buttonAlarmRefresh.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmRefresh.setObjectName("buttonAlarmRefresh")
        self.buttonAlarmStart = QtWidgets.QPushButton(Stopwatch)
        self.buttonAlarmStart.setGeometry(QtCore.QRect(90, 350, 51, 51))
        self.buttonAlarmStart.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonAlarmStart.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("start1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarmStart.setIcon(icon4)
        self.buttonAlarmStart.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmStart.setObjectName("buttonAlarmStart")
        self.buttonAlarmPause = QtWidgets.QPushButton(Stopwatch)
        self.buttonAlarmPause.setGeometry(QtCore.QRect(170, 350, 51, 51))
        self.buttonAlarmPause.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonAlarmPause.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarmPause.setIcon(icon5)
        self.buttonAlarmPause.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarmPause.setObjectName("buttonAlarmPause")

        self.retranslateUi(Stopwatch)
        QtCore.QMetaObject.connectSlotsByName(Stopwatch)

    def retranslateUi(self, Stopwatch):
        _translate = QtCore.QCoreApplication.translate
        Stopwatch.setWindowTitle(_translate("Stopwatch", "Form"))
        self.buttonTimer.setWhatsThis(_translate("Stopwatch", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonStopwatch.setWhatsThis(_translate("Stopwatch", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarm_2.setWhatsThis(_translate("Stopwatch", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmRefresh.setWhatsThis(_translate("Stopwatch", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmStart.setWhatsThis(_translate("Stopwatch", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarmPause.setWhatsThis(_translate("Stopwatch", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Stopwatch = QtWidgets.QWidget()
    ui = Ui_Stopwatch()
    ui.setupUi(Stopwatch)
    Stopwatch.show()
    sys.exit(app.exec_())
