# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName("Timer")
        Timer.resize(400, 600)
        Timer.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.buttonTimer = QtWidgets.QPushButton(Timer)
        self.buttonTimer.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.buttonTimer.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 0);")
        self.buttonTimer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimer.setIcon(icon)
        self.buttonTimer.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimer.setObjectName("buttonTimer")
        self.buttonAlarm = QtWidgets.QPushButton(Timer)
        self.buttonAlarm.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.buttonAlarm.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonAlarm.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("alarm-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarm.setIcon(icon1)
        self.buttonAlarm.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarm.setObjectName("buttonAlarm")
        self.buttonStopwatch = QtWidgets.QPushButton(Timer)
        self.buttonStopwatch.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.buttonStopwatch.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonStopwatch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("stopwatch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStopwatch.setIcon(icon2)
        self.buttonStopwatch.setIconSize(QtCore.QSize(32, 32))
        self.buttonStopwatch.setObjectName("buttonStopwatch")
        self.MainTimer = QtWidgets.QLCDNumber(Timer)
        self.MainTimer.setGeometry(QtCore.QRect(90, 210, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.MainTimer.setFont(font)
        self.MainTimer.setObjectName("MainTimer")
        self.buttonTimerStart = QtWidgets.QPushButton(Timer)
        self.buttonTimerStart.setGeometry(QtCore.QRect(90, 360, 51, 51))
        self.buttonTimerStart.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonTimerStart.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("start1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimerStart.setIcon(icon3)
        self.buttonTimerStart.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimerStart.setObjectName("buttonTimerStart")
        self.buttonTimerPause = QtWidgets.QPushButton(Timer)
        self.buttonTimerPause.setGeometry(QtCore.QRect(170, 360, 51, 51))
        self.buttonTimerPause.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonTimerPause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimerPause.setIcon(icon4)
        self.buttonTimerPause.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimerPause.setObjectName("buttonTimerPause")
        self.buttonTimerRefresh = QtWidgets.QPushButton(Timer)
        self.buttonTimerRefresh.setGeometry(QtCore.QRect(250, 360, 51, 51))
        self.buttonTimerRefresh.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonTimerRefresh.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimerRefresh.setIcon(icon5)
        self.buttonTimerRefresh.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimerRefresh.setObjectName("buttonTimerRefresh")
        self.buttonTimerPlus = QtWidgets.QPushButton(Timer)
        self.buttonTimerPlus.setGeometry(QtCore.QRect(10, 510, 381, 81))
        self.buttonTimerPlus.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 0);")
        self.buttonTimerPlus.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimerPlus.setIcon(icon6)
        self.buttonTimerPlus.setIconSize(QtCore.QSize(54, 54))
        self.buttonTimerPlus.setObjectName("buttonTimerPlus")

        self.retranslateUi(Timer)
        QtCore.QMetaObject.connectSlotsByName(Timer)

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Form"))
        self.buttonTimer.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarm.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonStopwatch.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonTimerStart.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonTimerPause.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonTimerRefresh.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonTimerPlus.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Timer = QtWidgets.QWidget()
    ui = Ui_Timer()
    ui.setupUi(Timer)
    Timer.show()
    sys.exit(app.exec_())
