# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName("Timer")
        Timer.resize(400, 600)
        Timer.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.buttonTimer = QtWidgets.QPushButton(Timer)
        self.buttonTimer.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.buttonTimer.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(255, 255, 0);")
        self.buttonTimer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("timer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonTimer.setIcon(icon)
        self.buttonTimer.setIconSize(QtCore.QSize(32, 32))
        self.buttonTimer.setObjectName("buttonTimer")
        self.buttonAlarm_2 = QtWidgets.QPushButton(Timer)
        self.buttonAlarm_2.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.buttonAlarm_2.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonAlarm_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("alarm-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAlarm_2.setIcon(icon1)
        self.buttonAlarm_2.setIconSize(QtCore.QSize(32, 32))
        self.buttonAlarm_2.setObjectName("buttonAlarm_2")
        self.buttonStopwatch = QtWidgets.QPushButton(Timer)
        self.buttonStopwatch.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.buttonStopwatch.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(175, 175, 175);")
        self.buttonStopwatch.setText("")
        self.buttonStopwatch.setIcon(icon)
        self.buttonStopwatch.setIconSize(QtCore.QSize(32, 32))
        self.buttonStopwatch.setObjectName("buttonStopwatch")
        self.MainTimer = QtWidgets.QLCDNumber(Timer)
        self.MainTimer.setGeometry(QtCore.QRect(90, 210, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.MainTimer.setFont(font)
        self.MainTimer.setObjectName("MainTimer")

        self.retranslateUi(Timer)
        QtCore.QMetaObject.connectSlotsByName(Timer)

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Form"))
        self.buttonTimer.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonAlarm_2.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonStopwatch.setWhatsThis(_translate("Timer", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Timer = QtWidgets.QWidget()
    ui = Ui_Timer()
    ui.setupUi(Timer)
    Timer.show()
    sys.exit(app.exec_())
